### ISSUE TITLE
How can I run this script?

### ISSUE THREAD

**Issue by RussiaVk** [myungjaeyu/dos#1]
Sorry, I'm a beginner

**Comment by vervoortkobe** [comment]
1. Install NodeJS
2. Create a folder where u want to store the files
3. Run CMD (command prompt)
4. cd into that folder (e.g.: cd C:\Users\Tsunami\Desktop\DoSScript)
5. type in CMD this: "npm install request" (this should create a node_modules folder)
6. Edit the index.js file (http://localhost:3000 to the ip u want to attack)
7. type in CMD this: "node index.js" (this should run the code)
